-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2017/3/3 17:22:31
-- Server version: 5.0.24a-community-nt
-- Client version: 4.1

USE monitorcenter;

CREATE TABLE person (
  PersonID int(11) NOT NULL AUTO_INCREMENT,
  PersonName varchar(50) NOT NULL DEFAULT '',
  Gender bit(1) DEFAULT NULL,
  Age int(11) NOT NULL,
  Birth date NOT NULL,
  Telephone varchar(20) DEFAULT NULL,
  Email varchar(50) DEFAULT NULL,
  Adress varchar(255) DEFAULT NULL,
  Company varchar(255) DEFAULT NULL,
  Department varchar(100) DEFAULT NULL,
  PRIMARY KEY (PersonID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '人员表';

CREATE TABLE sysroles (
  RoleID int(11) NOT NULL AUTO_INCREMENT,
  RoleName varchar(50) DEFAULT NULL,
  RoleParentID int(11) DEFAULT NULL,
  IsReadOnly bit(1) DEFAULT NULL,
  PRIMARY KEY (RoleID)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
AVG_ROW_LENGTH = 4096
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '用户权限表';

CREATE TABLE sysusers (
  UserID int(11) NOT NULL AUTO_INCREMENT,
  UserName varchar(50) NOT NULL DEFAULT '',
  PassWord varchar(100) DEFAULT NULL,
  PersonID int(11) DEFAULT NULL,
  CreateBy varchar(50) DEFAULT NULL,
  CreateDate date DEFAULT NULL,
  PRIMARY KEY (UserID),
  CONSTRAINT FK_sysusers_person_PersonID FOREIGN KEY (PersonID)
  REFERENCES person (PersonID) ON DELETE SET NULL ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '系统用户表';

CREATE TABLE useroles (
  UserID int(11) NOT NULL,
  RoleID int(11) NOT NULL,
  CONSTRAINT FK_useroles_sysroles_RoleID FOREIGN KEY (RoleID)
  REFERENCES sysroles (RoleID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_useroles_sysusers_UserID FOREIGN KEY (UserID)
  REFERENCES sysusers (UserID) ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

INSERT INTO monitorcenter.sysroles(RoleName ,RoleParentID ,IsReadOnly)
VALUES('佳讯',0,0),('路局',1,0),('线路',2,1),('线路2',2,1)